name: Run Python Script on Push

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        id: run_script
        run: |
          python deployment/ci/unicode_check.py

      - name: Print script output
        if: success()
        run: echo "✅ Script ran successfully."

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Script failed!"
